stages:
  preprocess:
    cmd: python src/preprocess.py data/data.csv data/clean_data.csv params.yaml
    deps:
    - data/data.csv
    - params.yaml
    outs:
    - data/clean_data.csv
  train:
    cmd: python src/train.py data/clean_data.csv models/model.pkl params.yaml
    deps:
    - data/clean_data.csv
    - params.yaml
    outs:
    - models/model.pkl
  evaluate:
    cmd: python src/evaluate.py models/model.pkl data/clean_data.csv params.yaml metrics.json
      params.yaml
    deps:
    - models/model.pkl
    - data/clean_data.csv
    - params.yaml
    metrics:
    - metrics.json:
        cache: false
  exploration:
    cmd: python src/exploration.py
    deps:
    - data/data.csv
    - params.yaml
    outs:
    - data/missing_values.txt
